from datetime import datetime
from typing import Any, Dict

from pydantic import BaseModel, ConfigDict, field_validator


class EventSchemaCreate(BaseModel):
    """
    Schema for creating an event schema.

    Version is auto-generated by incrementing the max version for the event_type.
    """

    event_type: str
    schema_definition: Dict[str, Any]

    @field_validator("event_type")
    @classmethod
    def validate_event_type(cls, v: str) -> str:
        if not v or not isinstance(v, str):
            raise ValueError("Event type must be a non-empty string")
        if not v.replace("_", "").isalnum():
            raise ValueError("Event type must contain only alphanumeric characters and underscores")
        return v.lower()

    @field_validator("schema_definition")
    @classmethod
    def validate_schema_definition(cls, v: Dict[str, Any]) -> Dict[str, Any]:
        if not v:
            raise ValueError("Schema definition cannot be empty")
        if "type" not in v:
            raise ValueError("Schema must have a 'type' field (JSON Schema requirement)")
        return v


class EventSchemaUpdate(BaseModel):
    """Schema for updating an event schema"""

    is_active: bool | None = None


class EventSchemaResponse(BaseModel):
    """Schema for event schema responses"""

    id: str
    tenant_id: str
    event_type: str
    schema_definition: Dict[str, Any]
    version: int
    is_active: bool
    created_by: str | None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
