"""refactor models to use mixins system

Revision ID: 086f991ff6d7
Revises: 789b7fad5023
Create Date: 2025-12-28 09:23:06.698192

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "086f991ff6d7"
down_revision: Union[str, Sequence[str], None] = "789b7fad5023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "document",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_document_created_by"), "document", ["created_by"], unique=False)
    op.create_index(op.f("ix_document_deleted_at"), "document", ["deleted_at"], unique=False)
    op.drop_constraint(op.f("document_tenant_id_fkey"), "document", type_="foreignkey")
    op.create_foreign_key(None, "document", "tenant", ["tenant_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "document", "user", ["created_by"], ["id"], ondelete="SET NULL")
    op.alter_column(
        "email_account",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "email_account",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("email_account_tenant_id_fkey"), "email_account", type_="foreignkey")
    op.create_foreign_key(
        None, "email_account", "tenant", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index(op.f("ix_event_type_version"), table_name="event")
    op.create_index(
        "ix_event_tenant_type_version",
        "event",
        ["tenant_id", "event_type", "schema_version"],
        unique=False,
    )
    op.drop_constraint(op.f("event_tenant_id_fkey"), "event", type_="foreignkey")
    op.create_foreign_key(None, "event", "tenant", ["tenant_id"], ["id"], ondelete="CASCADE")
    op.create_index(
        op.f("ix_event_schema_created_by"), "event_schema", ["created_by"], unique=False
    )
    op.drop_constraint(op.f("fk_event_schema_created_by_user"), "event_schema", type_="foreignkey")
    op.create_foreign_key(None, "event_schema", "user", ["created_by"], ["id"], ondelete="SET NULL")
    op.drop_column("permission", "created_at")
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("role_permission", "created_at")
    op.alter_column(
        "subject",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("subject_tenant_id_fkey"), "subject", type_="foreignkey")
    op.create_foreign_key(None, "subject", "tenant", ["tenant_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "tenant",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_role",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("user_role_assigned_by_fkey"), "user_role", type_="foreignkey")
    op.create_foreign_key(None, "user_role", "user", ["assigned_by"], ["id"], ondelete="SET NULL")
    op.add_column("workflow", sa.Column("updated_by", sa.String(), nullable=True))
    op.add_column("workflow", sa.Column("deleted_by", sa.String(), nullable=True))
    op.create_index(op.f("ix_workflow_created_by"), "workflow", ["created_by"], unique=False)
    op.create_index(op.f("ix_workflow_deleted_at"), "workflow", ["deleted_at"], unique=False)
    op.create_foreign_key(None, "workflow", "user", ["updated_by"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "workflow", "user", ["created_by"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "workflow", "user", ["deleted_by"], ["id"], ondelete="SET NULL")
    op.add_column(
        "workflow_execution",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_workflow_execution_created_at"), table_name="workflow_execution")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_workflow_execution_created_at"),
        "workflow_execution",
        ["created_at"],
        unique=False,
    )
    op.drop_column("workflow_execution", "updated_at")
    op.drop_constraint(None, "workflow", type_="foreignkey")
    op.drop_constraint(None, "workflow", type_="foreignkey")
    op.drop_constraint(None, "workflow", type_="foreignkey")
    op.drop_index(op.f("ix_workflow_deleted_at"), table_name="workflow")
    op.drop_index(op.f("ix_workflow_created_by"), table_name="workflow")
    op.drop_column("workflow", "deleted_by")
    op.drop_column("workflow", "updated_by")
    op.drop_constraint(None, "user_role", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_role_assigned_by_fkey"), "user_role", "user", ["assigned_by"], ["id"]
    )
    op.alter_column(
        "user_role",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "subject", type_="foreignkey")
    op.create_foreign_key(
        op.f("subject_tenant_id_fkey"), "subject", "tenant", ["tenant_id"], ["id"]
    )
    op.alter_column(
        "subject",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "role_permission",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "role",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "permission",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "event_schema", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_event_schema_created_by_user"),
        "event_schema",
        "user",
        ["created_by"],
        ["id"],
    )
    op.drop_index(op.f("ix_event_schema_created_by"), table_name="event_schema")
    op.drop_constraint(None, "event", type_="foreignkey")
    op.create_foreign_key(op.f("event_tenant_id_fkey"), "event", "tenant", ["tenant_id"], ["id"])
    op.drop_index("ix_event_tenant_type_version", table_name="event")
    op.create_index(
        op.f("ix_event_type_version"),
        "event",
        ["event_type", "schema_version"],
        unique=False,
    )
    op.drop_constraint(None, "email_account", type_="foreignkey")
    op.create_foreign_key(
        op.f("email_account_tenant_id_fkey"),
        "email_account",
        "tenant",
        ["tenant_id"],
        ["id"],
    )
    op.alter_column(
        "email_account",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "email_account",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "document", type_="foreignkey")
    op.drop_constraint(None, "document", type_="foreignkey")
    op.create_foreign_key(
        op.f("document_tenant_id_fkey"), "document", "tenant", ["tenant_id"], ["id"]
    )
    op.drop_index(op.f("ix_document_deleted_at"), table_name="document")
    op.drop_index(op.f("ix_document_created_by"), table_name="document")
    op.alter_column(
        "document",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("document", "updated_at")
    # ### end Alembic commands ###
