"""Add email_account table for integration metadata

Revision ID: ba0e2857597d
Revises: f61af9c8e951
Create Date: 2025-12-17 08:45:04.755638

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ba0e2857597d"
down_revision: Union[str, Sequence[str], None] = "f61af9c8e951"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_account",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("subject_id", sa.String(), nullable=False),
        sa.Column("provider_type", sa.String(), nullable=False),
        sa.Column("email_address", sa.String(), nullable=False),
        sa.Column("credentials_encrypted", sa.String(), nullable=False),
        sa.Column("connection_params", sa.JSON(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("webhook_id", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_account_email_address"),
        "email_account",
        ["email_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_account_subject_id"),
        "email_account",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_account_tenant_id"), "email_account", ["tenant_id"], unique=False
    )
    op.alter_column(
        "workflow",
        "trigger_event_type",
        existing_type=sa.VARCHAR(),
        comment="Event type that triggers this workflow",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow",
        "trigger_conditions",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Optional JSON conditions (JSONPath expressions)",
        existing_nullable=True,
    )
    op.alter_column(
        "workflow",
        "actions",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Array of actions to execute [{type, params}, ...]",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow",
        "max_executions_per_day",
        existing_type=sa.INTEGER(),
        comment="Rate limit: max executions per day (null = unlimited)",
        existing_nullable=True,
    )
    op.alter_column(
        "workflow",
        "execution_order",
        existing_type=sa.INTEGER(),
        comment="Execution priority (lower = earlier)",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_execution",
        "triggered_by_event_id",
        existing_type=sa.VARCHAR(),
        comment="Event that triggered this workflow",
        existing_nullable=True,
    )
    op.alter_column(
        "workflow_execution",
        "status",
        existing_type=sa.VARCHAR(),
        comment="pending | running | completed | failed",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_execution",
        "actions_executed",
        existing_type=sa.INTEGER(),
        comment="Number of actions successfully executed",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_execution",
        "actions_failed",
        existing_type=sa.INTEGER(),
        comment="Number of actions that failed",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_execution",
        "execution_log",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Detailed execution log with action results",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_execution",
        "execution_log",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="Detailed execution log with action results",
        existing_nullable=True,
    )
    op.alter_column(
        "workflow_execution",
        "actions_failed",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Number of actions that failed",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_execution",
        "actions_executed",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Number of actions successfully executed",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_execution",
        "status",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="pending | running | completed | failed",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_execution",
        "triggered_by_event_id",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Event that triggered this workflow",
        existing_nullable=True,
    )
    op.alter_column(
        "workflow",
        "execution_order",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Execution priority (lower = earlier)",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow",
        "max_executions_per_day",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Rate limit: max executions per day (null = unlimited)",
        existing_nullable=True,
    )
    op.alter_column(
        "workflow",
        "actions",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="Array of actions to execute [{type, params}, ...]",
        existing_nullable=False,
    )
    op.alter_column(
        "workflow",
        "trigger_conditions",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="Optional JSON conditions (JSONPath expressions)",
        existing_nullable=True,
    )
    op.alter_column(
        "workflow",
        "trigger_event_type",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Event type that triggers this workflow",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_email_account_tenant_id"), table_name="email_account")
    op.drop_index(op.f("ix_email_account_subject_id"), table_name="email_account")
    op.drop_index(op.f("ix_email_account_email_address"), table_name="email_account")
    op.drop_table("email_account")
    # ### end Alembic commands ###
