"""add_workflow_tables

Revision ID: e469986dce88
Revises: 9e1aedfa0671
Create Date: 2025-12-17 03:50:28.515568

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e469986dce88"
down_revision: Union[str, Sequence[str], None] = "9e1aedfa0671"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create workflow tables
    op.create_table(
        "workflow",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("trigger_event_type", sa.String(), nullable=False),
        sa.Column("trigger_conditions", sa.JSON(), nullable=True),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("max_executions_per_day", sa.Integer(), nullable=True),
        sa.Column("execution_order", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_workflow_tenant_id", "workflow", ["tenant_id"])
    op.create_index("ix_workflow_trigger_event_type", "workflow", ["trigger_event_type"])

    op.create_table(
        "workflow_execution",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("triggered_by_event_id", sa.String(), nullable=True),
        sa.Column("triggered_by_subject_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actions_executed", sa.Integer(), nullable=False),
        sa.Column("actions_failed", sa.Integer(), nullable=False),
        sa.Column("execution_log", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflow.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["triggered_by_event_id"], ["event.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["triggered_by_subject_id"], ["subject.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_workflow_execution_tenant_id", "workflow_execution", ["tenant_id"])
    op.create_index("ix_workflow_execution_workflow_id", "workflow_execution", ["workflow_id"])
    op.create_index(
        "ix_workflow_execution_triggered_by_event_id",
        "workflow_execution",
        ["triggered_by_event_id"],
    )
    op.create_index(
        "ix_workflow_execution_triggered_by_subject_id",
        "workflow_execution",
        ["triggered_by_subject_id"],
    )
    op.create_index("ix_workflow_execution_created_at", "workflow_execution", ["created_at"])

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document",
        "file_size",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column("document", "is_latest_version", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index(op.f("ix_document_tenant_checksum"), table_name="document")
    op.create_index(
        "ix_document_checksum_unique",
        "document",
        ["tenant_id", "checksum"],
        unique=True,
    )
    op.create_index(
        "ix_document_tenant_subject",
        "document",
        ["tenant_id", "subject_id"],
        unique=False,
    )
    op.create_index(
        "ux_document_versions",
        "document",
        ["tenant_id", "subject_id", "parent_document_id", "version"],
        unique=True,
    )
    op.drop_constraint(op.f("event_hash_key"), "event", type_="unique")
    op.drop_index(op.f("ix_event_schema_active"), table_name="event_schema")
    op.alter_column(
        "permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role_permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("tenant_code_key"), "tenant", type_="unique")
    # Fix user.is_active type conversion
    op.execute('ALTER TABLE "user" ALTER COLUMN is_active DROP DEFAULT')
    op.execute('ALTER TABLE "user" ALTER COLUMN is_active TYPE BOOLEAN USING is_active::boolean')
    op.execute('ALTER TABLE "user" ALTER COLUMN is_active SET DEFAULT true')
    op.alter_column(
        "user_role",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("user_role_assigned_by_fkey"), "user_role", type_="foreignkey")
    op.create_foreign_key(None, "user_role", "user", ["assigned_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop workflow tables
    op.drop_index("ix_workflow_execution_created_at", table_name="workflow_execution")
    op.drop_index("ix_workflow_execution_triggered_by_subject_id", table_name="workflow_execution")
    op.drop_index("ix_workflow_execution_triggered_by_event_id", table_name="workflow_execution")
    op.drop_index("ix_workflow_execution_workflow_id", table_name="workflow_execution")
    op.drop_index("ix_workflow_execution_tenant_id", table_name="workflow_execution")
    op.drop_table("workflow_execution")

    op.drop_index("ix_workflow_trigger_event_type", table_name="workflow")
    op.drop_index("ix_workflow_tenant_id", table_name="workflow")
    op.drop_table("workflow")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_role", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_role_assigned_by_fkey"),
        "user_role",
        "user",
        ["assigned_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "user_role",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user",
        "is_active",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        existing_server_default=sa.text("'true'::character varying"),
    )
    op.create_unique_constraint(op.f("tenant_code_key"), "tenant", ["code"])
    op.alter_column(
        "role_permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "permission",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_event_schema_active"),
        "event_schema",
        ["tenant_id", "event_type", "is_active"],
        unique=False,
    )
    op.create_unique_constraint(op.f("event_hash_key"), "event", ["hash"])
    op.drop_index("ux_document_versions", table_name="document")
    op.drop_index("ix_document_tenant_subject", table_name="document")
    op.drop_index("ix_document_checksum_unique", table_name="document")
    op.create_index(
        op.f("ix_document_tenant_checksum"),
        "document",
        ["tenant_id", "checksum"],
        unique=False,
    )
    op.alter_column("document", "is_latest_version", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "document",
        "file_size",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
