"""Firebase Admin SDK and Firestore integration."""

from app.infrastructure.firebase.client import (
    get_firestore_client,
    init_firebase,
)
from app.infrastructure.firebase.collections import (
    COLLECTION_DOCUMENTS,
    COLLECTION_EMAIL_ACCOUNTS,
    COLLECTION_EVENT_SCHEMAS,
    COLLECTION_EVENTS,
    COLLECTION_OAUTH_PROVIDER_CONFIGS,
    COLLECTION_PERMISSIONS,
    COLLECTION_ROLE_PERMISSIONS,
    COLLECTION_ROLES,
    COLLECTION_SUBJECTS,
    COLLECTION_TENANTS,
    COLLECTION_USER_ROLES,
    COLLECTION_USERS,
    COLLECTION_WORKFLOW_EXECUTIONS,
    COLLECTION_WORKFLOWS,
)

__all__ = [
    "get_firestore_client",
    "init_firebase",
    "COLLECTION_DOCUMENTS",
    "COLLECTION_EMAIL_ACCOUNTS",
    "COLLECTION_EVENT_SCHEMAS",
    "COLLECTION_EVENTS",
    "COLLECTION_OAUTH_PROVIDER_CONFIGS",
    "COLLECTION_PERMISSIONS",
    "COLLECTION_ROLE_PERMISSIONS",
    "COLLECTION_ROLES",
    "COLLECTION_SUBJECTS",
    "COLLECTION_TENANTS",
    "COLLECTION_USER_ROLES",
    "COLLECTION_USERS",
    "COLLECTION_WORKFLOW_EXECUTIONS",
    "COLLECTION_WORKFLOWS",
]
