/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EmailAccountsIndexRouteImport } from './routes/email-accounts/index'
import { Route as VerifyTenantRouteImport } from './routes/verify/tenant'
import { Route as VerifySubjectIdRouteImport } from './routes/verify/$subjectId'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects/$subjectId'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EmailAccountsCreateRouteImport } from './routes/email-accounts/create'
import { Route as EmailAccountsAccountIdRouteImport } from './routes/email-accounts/$accountId'
import { Route as SettingsWorkflowsIndexRouteImport } from './routes/settings/workflows/index'
import { Route as SettingsUsersIndexRouteImport } from './routes/settings/users/index'
import { Route as SettingsSubjectTypesIndexRouteImport } from './routes/settings/subject-types/index'
import { Route as SettingsSchemasIndexRouteImport } from './routes/settings/schemas/index'
import { Route as SettingsRolesIndexRouteImport } from './routes/settings/roles/index'
import { Route as SettingsPermissionsIndexRouteImport } from './routes/settings/permissions/index'
import { Route as SettingsOauthProvidersIndexRouteImport } from './routes/settings/oauth-providers/index'
import { Route as SettingsDocumentCategoriesIndexRouteImport } from './routes/settings/document-categories/index'
import { Route as SettingsAuditLogIndexRouteImport } from './routes/settings/audit-log/index'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles/index'
import { Route as AdminPermissionsIndexRouteImport } from './routes/admin/permissions/index'
import { Route as EventsSubjectSubjectIdRouteImport } from './routes/events/subject.$subjectId'
import { Route as EmailAccountsOauthCallbackRouteImport } from './routes/email-accounts/oauth/callback'
import { Route as SubjectsSubjectIdEventsEventIdRouteImport } from './routes/subjects/$subjectId_/events/$eventId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAccountsIndexRoute = EmailAccountsIndexRouteImport.update({
  id: '/email-accounts/',
  path: '/email-accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTenantRoute = VerifyTenantRouteImport.update({
  id: '/verify/tenant',
  path: '/verify/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySubjectIdRoute = VerifySubjectIdRouteImport.update({
  id: '/verify/$subjectId',
  path: '/verify/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAccountsCreateRoute = EmailAccountsCreateRouteImport.update({
  id: '/email-accounts/create',
  path: '/email-accounts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAccountsAccountIdRoute = EmailAccountsAccountIdRouteImport.update({
  id: '/email-accounts/$accountId',
  path: '/email-accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWorkflowsIndexRoute = SettingsWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersIndexRoute = SettingsUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSubjectTypesIndexRoute =
  SettingsSubjectTypesIndexRouteImport.update({
    id: '/subject-types/',
    path: '/subject-types/',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSchemasIndexRoute = SettingsSchemasIndexRouteImport.update({
  id: '/schemas/',
  path: '/schemas/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesIndexRoute = SettingsRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPermissionsIndexRoute =
  SettingsPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsOauthProvidersIndexRoute =
  SettingsOauthProvidersIndexRouteImport.update({
    id: '/oauth-providers/',
    path: '/oauth-providers/',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsDocumentCategoriesIndexRoute =
  SettingsDocumentCategoriesIndexRouteImport.update({
    id: '/document-categories/',
    path: '/document-categories/',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsAuditLogIndexRoute = SettingsAuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => SettingsRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/admin/roles/',
  path: '/admin/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsIndexRoute = AdminPermissionsIndexRouteImport.update({
  id: '/admin/permissions/',
  path: '/admin/permissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSubjectSubjectIdRoute = EventsSubjectSubjectIdRouteImport.update({
  id: '/events/subject/$subjectId',
  path: '/events/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAccountsOauthCallbackRoute =
  EmailAccountsOauthCallbackRouteImport.update({
    id: '/email-accounts/oauth/callback',
    path: '/email-accounts/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const SubjectsSubjectIdEventsEventIdRoute =
  SubjectsSubjectIdEventsEventIdRouteImport.update({
    id: '/subjects/$subjectId_/events/$eventId',
    path: '/subjects/$subjectId/events/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/email-accounts/$accountId': typeof EmailAccountsAccountIdRoute
  '/email-accounts/create': typeof EmailAccountsCreateRoute
  '/events/create': typeof EventsCreateRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/verify/$subjectId': typeof VerifySubjectIdRoute
  '/verify/tenant': typeof VerifyTenantRoute
  '/email-accounts/': typeof EmailAccountsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/email-accounts/oauth/callback': typeof EmailAccountsOauthCallbackRoute
  '/events/subject/$subjectId': typeof EventsSubjectSubjectIdRoute
  '/admin/permissions/': typeof AdminPermissionsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/settings/audit-log/': typeof SettingsAuditLogIndexRoute
  '/settings/document-categories/': typeof SettingsDocumentCategoriesIndexRoute
  '/settings/oauth-providers/': typeof SettingsOauthProvidersIndexRoute
  '/settings/permissions/': typeof SettingsPermissionsIndexRoute
  '/settings/roles/': typeof SettingsRolesIndexRoute
  '/settings/schemas/': typeof SettingsSchemasIndexRoute
  '/settings/subject-types/': typeof SettingsSubjectTypesIndexRoute
  '/settings/users/': typeof SettingsUsersIndexRoute
  '/settings/workflows/': typeof SettingsWorkflowsIndexRoute
  '/subjects/$subjectId/events/$eventId': typeof SubjectsSubjectIdEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/email-accounts/$accountId': typeof EmailAccountsAccountIdRoute
  '/email-accounts/create': typeof EmailAccountsCreateRoute
  '/events/create': typeof EventsCreateRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/verify/$subjectId': typeof VerifySubjectIdRoute
  '/verify/tenant': typeof VerifyTenantRoute
  '/email-accounts': typeof EmailAccountsIndexRoute
  '/events': typeof EventsIndexRoute
  '/search': typeof SearchIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/email-accounts/oauth/callback': typeof EmailAccountsOauthCallbackRoute
  '/events/subject/$subjectId': typeof EventsSubjectSubjectIdRoute
  '/admin/permissions': typeof AdminPermissionsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/settings/audit-log': typeof SettingsAuditLogIndexRoute
  '/settings/document-categories': typeof SettingsDocumentCategoriesIndexRoute
  '/settings/oauth-providers': typeof SettingsOauthProvidersIndexRoute
  '/settings/permissions': typeof SettingsPermissionsIndexRoute
  '/settings/roles': typeof SettingsRolesIndexRoute
  '/settings/schemas': typeof SettingsSchemasIndexRoute
  '/settings/subject-types': typeof SettingsSubjectTypesIndexRoute
  '/settings/users': typeof SettingsUsersIndexRoute
  '/settings/workflows': typeof SettingsWorkflowsIndexRoute
  '/subjects/$subjectId/events/$eventId': typeof SubjectsSubjectIdEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/email-accounts/$accountId': typeof EmailAccountsAccountIdRoute
  '/email-accounts/create': typeof EmailAccountsCreateRoute
  '/events/create': typeof EventsCreateRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/verify/$subjectId': typeof VerifySubjectIdRoute
  '/verify/tenant': typeof VerifyTenantRoute
  '/email-accounts/': typeof EmailAccountsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/email-accounts/oauth/callback': typeof EmailAccountsOauthCallbackRoute
  '/events/subject/$subjectId': typeof EventsSubjectSubjectIdRoute
  '/admin/permissions/': typeof AdminPermissionsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/settings/audit-log/': typeof SettingsAuditLogIndexRoute
  '/settings/document-categories/': typeof SettingsDocumentCategoriesIndexRoute
  '/settings/oauth-providers/': typeof SettingsOauthProvidersIndexRoute
  '/settings/permissions/': typeof SettingsPermissionsIndexRoute
  '/settings/roles/': typeof SettingsRolesIndexRoute
  '/settings/schemas/': typeof SettingsSchemasIndexRoute
  '/settings/subject-types/': typeof SettingsSubjectTypesIndexRoute
  '/settings/users/': typeof SettingsUsersIndexRoute
  '/settings/workflows/': typeof SettingsWorkflowsIndexRoute
  '/subjects/$subjectId_/events/$eventId': typeof SubjectsSubjectIdEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/email-accounts/$accountId'
    | '/email-accounts/create'
    | '/events/create'
    | '/subjects/$subjectId'
    | '/verify/$subjectId'
    | '/verify/tenant'
    | '/email-accounts/'
    | '/events/'
    | '/search/'
    | '/subjects/'
    | '/email-accounts/oauth/callback'
    | '/events/subject/$subjectId'
    | '/admin/permissions/'
    | '/admin/roles/'
    | '/settings/audit-log/'
    | '/settings/document-categories/'
    | '/settings/oauth-providers/'
    | '/settings/permissions/'
    | '/settings/roles/'
    | '/settings/schemas/'
    | '/settings/subject-types/'
    | '/settings/users/'
    | '/settings/workflows/'
    | '/subjects/$subjectId/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/email-accounts/$accountId'
    | '/email-accounts/create'
    | '/events/create'
    | '/subjects/$subjectId'
    | '/verify/$subjectId'
    | '/verify/tenant'
    | '/email-accounts'
    | '/events'
    | '/search'
    | '/subjects'
    | '/email-accounts/oauth/callback'
    | '/events/subject/$subjectId'
    | '/admin/permissions'
    | '/admin/roles'
    | '/settings/audit-log'
    | '/settings/document-categories'
    | '/settings/oauth-providers'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/schemas'
    | '/settings/subject-types'
    | '/settings/users'
    | '/settings/workflows'
    | '/subjects/$subjectId/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/email-accounts/$accountId'
    | '/email-accounts/create'
    | '/events/create'
    | '/subjects/$subjectId'
    | '/verify/$subjectId'
    | '/verify/tenant'
    | '/email-accounts/'
    | '/events/'
    | '/search/'
    | '/subjects/'
    | '/email-accounts/oauth/callback'
    | '/events/subject/$subjectId'
    | '/admin/permissions/'
    | '/admin/roles/'
    | '/settings/audit-log/'
    | '/settings/document-categories/'
    | '/settings/oauth-providers/'
    | '/settings/permissions/'
    | '/settings/roles/'
    | '/settings/schemas/'
    | '/settings/subject-types/'
    | '/settings/users/'
    | '/settings/workflows/'
    | '/subjects/$subjectId_/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  EmailAccountsAccountIdRoute: typeof EmailAccountsAccountIdRoute
  EmailAccountsCreateRoute: typeof EmailAccountsCreateRoute
  EventsCreateRoute: typeof EventsCreateRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  VerifySubjectIdRoute: typeof VerifySubjectIdRoute
  VerifyTenantRoute: typeof VerifyTenantRoute
  EmailAccountsIndexRoute: typeof EmailAccountsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  EmailAccountsOauthCallbackRoute: typeof EmailAccountsOauthCallbackRoute
  EventsSubjectSubjectIdRoute: typeof EventsSubjectSubjectIdRoute
  AdminPermissionsIndexRoute: typeof AdminPermissionsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  SubjectsSubjectIdEventsEventIdRoute: typeof SubjectsSubjectIdEventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-accounts/': {
      id: '/email-accounts/'
      path: '/email-accounts'
      fullPath: '/email-accounts/'
      preLoaderRoute: typeof EmailAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/tenant': {
      id: '/verify/tenant'
      path: '/verify/tenant'
      fullPath: '/verify/tenant'
      preLoaderRoute: typeof VerifyTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$subjectId': {
      id: '/verify/$subjectId'
      path: '/verify/$subjectId'
      fullPath: '/verify/$subjectId'
      preLoaderRoute: typeof VerifySubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-accounts/create': {
      id: '/email-accounts/create'
      path: '/email-accounts/create'
      fullPath: '/email-accounts/create'
      preLoaderRoute: typeof EmailAccountsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-accounts/$accountId': {
      id: '/email-accounts/$accountId'
      path: '/email-accounts/$accountId'
      fullPath: '/email-accounts/$accountId'
      preLoaderRoute: typeof EmailAccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/workflows/': {
      id: '/settings/workflows/'
      path: '/workflows'
      fullPath: '/settings/workflows/'
      preLoaderRoute: typeof SettingsWorkflowsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users/': {
      id: '/settings/users/'
      path: '/users'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof SettingsUsersIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/subject-types/': {
      id: '/settings/subject-types/'
      path: '/subject-types'
      fullPath: '/settings/subject-types/'
      preLoaderRoute: typeof SettingsSubjectTypesIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/schemas/': {
      id: '/settings/schemas/'
      path: '/schemas'
      fullPath: '/settings/schemas/'
      preLoaderRoute: typeof SettingsSchemasIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles/': {
      id: '/settings/roles/'
      path: '/roles'
      fullPath: '/settings/roles/'
      preLoaderRoute: typeof SettingsRolesIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/permissions/': {
      id: '/settings/permissions/'
      path: '/permissions'
      fullPath: '/settings/permissions/'
      preLoaderRoute: typeof SettingsPermissionsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/oauth-providers/': {
      id: '/settings/oauth-providers/'
      path: '/oauth-providers'
      fullPath: '/settings/oauth-providers/'
      preLoaderRoute: typeof SettingsOauthProvidersIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/document-categories/': {
      id: '/settings/document-categories/'
      path: '/document-categories'
      fullPath: '/settings/document-categories/'
      preLoaderRoute: typeof SettingsDocumentCategoriesIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audit-log/': {
      id: '/settings/audit-log/'
      path: '/audit-log'
      fullPath: '/settings/audit-log/'
      preLoaderRoute: typeof SettingsAuditLogIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions/': {
      id: '/admin/permissions/'
      path: '/admin/permissions'
      fullPath: '/admin/permissions/'
      preLoaderRoute: typeof AdminPermissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/subject/$subjectId': {
      id: '/events/subject/$subjectId'
      path: '/events/subject/$subjectId'
      fullPath: '/events/subject/$subjectId'
      preLoaderRoute: typeof EventsSubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-accounts/oauth/callback': {
      id: '/email-accounts/oauth/callback'
      path: '/email-accounts/oauth/callback'
      fullPath: '/email-accounts/oauth/callback'
      preLoaderRoute: typeof EmailAccountsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId_/events/$eventId': {
      id: '/subjects/$subjectId_/events/$eventId'
      path: '/subjects/$subjectId/events/$eventId'
      fullPath: '/subjects/$subjectId/events/$eventId'
      preLoaderRoute: typeof SubjectsSubjectIdEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAuditLogIndexRoute: typeof SettingsAuditLogIndexRoute
  SettingsDocumentCategoriesIndexRoute: typeof SettingsDocumentCategoriesIndexRoute
  SettingsOauthProvidersIndexRoute: typeof SettingsOauthProvidersIndexRoute
  SettingsPermissionsIndexRoute: typeof SettingsPermissionsIndexRoute
  SettingsRolesIndexRoute: typeof SettingsRolesIndexRoute
  SettingsSchemasIndexRoute: typeof SettingsSchemasIndexRoute
  SettingsSubjectTypesIndexRoute: typeof SettingsSubjectTypesIndexRoute
  SettingsUsersIndexRoute: typeof SettingsUsersIndexRoute
  SettingsWorkflowsIndexRoute: typeof SettingsWorkflowsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAuditLogIndexRoute: SettingsAuditLogIndexRoute,
  SettingsDocumentCategoriesIndexRoute: SettingsDocumentCategoriesIndexRoute,
  SettingsOauthProvidersIndexRoute: SettingsOauthProvidersIndexRoute,
  SettingsPermissionsIndexRoute: SettingsPermissionsIndexRoute,
  SettingsRolesIndexRoute: SettingsRolesIndexRoute,
  SettingsSchemasIndexRoute: SettingsSchemasIndexRoute,
  SettingsSubjectTypesIndexRoute: SettingsSubjectTypesIndexRoute,
  SettingsUsersIndexRoute: SettingsUsersIndexRoute,
  SettingsWorkflowsIndexRoute: SettingsWorkflowsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  EmailAccountsAccountIdRoute: EmailAccountsAccountIdRoute,
  EmailAccountsCreateRoute: EmailAccountsCreateRoute,
  EventsCreateRoute: EventsCreateRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  VerifySubjectIdRoute: VerifySubjectIdRoute,
  VerifyTenantRoute: VerifyTenantRoute,
  EmailAccountsIndexRoute: EmailAccountsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  EmailAccountsOauthCallbackRoute: EmailAccountsOauthCallbackRoute,
  EventsSubjectSubjectIdRoute: EventsSubjectSubjectIdRoute,
  AdminPermissionsIndexRoute: AdminPermissionsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  SubjectsSubjectIdEventsEventIdRoute: SubjectsSubjectIdEventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
